### PR TITLE
Set dump index from ACTIVEVIEW

### LINKED ISSUE #3113: The memory window does not correctly locate the address in the correct window.
### Operating System

Windows 11 Insider Preview 230609-1655

### x64dbg Version

Jun 15 2023

### Describe the issue

When I locate the memory in the detached window, it is not located in the detached memory window, but is located in the [Memory 1] window by default

### Steps to reproduce

1. Detach the memory window 2 or 3,4,5
2. locate the memory(in the current window) in the detached window and you will see, it just located in the memory 1 window.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by HayFieldLaps**
Fixes #3113 and #1596.

Fixes an issue with the "Follow DWORD/QWORD in Current Dump" commmand, as well as the "Go to..." expression box when a dump view is detached. It's not the most elegant but it's not terrible either.

If nativeTitle is ever changed [here](https://github.com/x64dbg/x64dbg/blob/6a970e657dc2279c9d2f584dc56cea14a2ba3e2f/src/gui/Src/Gui/CPUMultiDump.cpp#L30) this fix will break. The current user set dump view name does not affect this, nor does any language changes.

### CODE REVIEW

File: src/dbg/commands/cmd-gui.cpp [hunk 1]
```diff
@@ -46,6 +48,16 @@ bool cbDebugDump(int argc, char* argv[])
         }
         GuiDumpAtN(addr, int(index));
     }
+    else if(strcmp(activeView.title, "Dump 1") == 0)
```
Comment (mrexodia) [inline src/dbg/commands/cmd-gui.cpp:51]: This would probably be better to do as a regex to support additional dumps, but otherwise looks good!

**Review by mrexodia — CHANGES_REQUESTED** [review]

**Comment by torusrxxx** [comment]
nativeTitle will never be changed.

File: src/dbg/commands/cmd-gui.cpp [hunk 2]
```diff
@@ -47,7 +48,20 @@ bool cbDebugDump(int argc, char* argv[])
...
     }
     else
-        GuiDumpAt(addr);
+    {
+        ACTIVEVIEW activeView;
+        GuiGetActiveView(&activeView);
+        std::string titleString = activeView.title;
+        std::regex dumpPattern("Dump ([1-9][0-9]*)");
+        std::smatch matchResult;
+        if(std::regex_match(titleString, matchResult, dumpPattern))
```
Comment (ZehMatt) [inline src/dbg/commands/cmd-gui.cpp:57]: Does this really need regex? sscanf should do the trick with `Dump %d`

Comment (mrexodia) [reply src/dbg/commands/cmd-gui.cpp:57]: Yeah I’ll fix this once I’m back home.

**Comment by HayFieldLaps** [comment]
Switched the code to use sscanf_s, this is much nicer than using regex. I took your request too literally haha, probably should have thought of this myself.

**Comment by mrexodia** [comment]
Thanks!

**Comment by justanotheranonymoususer** [comment]
Unfortunately I can still repro https://github.com/x64dbg/x64dbg/issues/1596 in version November 7 2023 of the debugger
