### PR TITLE
Resolve UI bug (#715) and do not require restart on settings change

### LINKED ISSUE #715: The disassembly interface is too messy
x64dbg-disassembly-messy
New installation with default settings.

### PR DESCRIPTION
**Pull request by torusrxxx**
Now we don't need to restart the program to apply new disassembly settings.
And fix #715 (The disassembly interface is too messy)

---
This change is [Reviewable](https://reviewable.io/reviews/x64dbg/x64dbg/717)

### CODE REVIEW

File: src/gui/Src/Utils/CachedFontMetrics.h [hunk 1]
```diff
@@ -13,6 +13,7 @@ class CachedFontMetrics : public QObject
         : QObject(parent),
           mFontMetrics(font)
     {
+        memset(mWidths, 0, sizeof(mWidths));
```
Comment (mrexodia) [inline src/gui/Src/Utils/CachedFontMetrics.h]: ahh that was the problem. At first I had this but I tried some things and then removed it again :disappointed:

**Comment by mrexodia** [comment]
thanks a lot!
